#pragma once

#include <libcpp_config.hpp>

#ifndef LIBCPP_SLOW
#define LIBCPP_SLOW 0
#endif

#ifndef LIBCPP_ENABLE_ASSERT
#define LIBCPP_ENABLE_ASSERT 1
#endif

#ifndef LIBCPP_USE_LIBC
#define LIBCPP_USE_LIBC 1
#endif

#ifndef LIBCPP_ARENA_DEFAULT_BLOCK_SIZE
#define LIBCPP_ARENA_DEFAULT_BLOCK_SIZE MEBI(16)
#endif

#ifndef LIBCPP_HEAP_DEFAULT_BLOCK_SIZE
#define LIBCPP_HEAP_DEFAULT_BLOCK_SIZE MEBI(8)
#endif

#ifndef LIBCPP_HEAP_DEFAULT_CHUNK_COUNT
#define LIBCPP_HEAP_DEFAULT_CHUNK_COUNT KIBI(8)
#endif

#ifndef LIBCPP_HEAP_DEFAULT_SPLIT_THRESHOLD
#define LIBCPP_HEAP_DEFAULT_SPLIT_THRESHOLD KIBI(1)
#endif

